### ISSUE TITLE
ESLint configuration overrides via inline comments do not work as expected.

### ISSUE THREAD

**Issue by jdickey** [jdickey/flix#3]
In a variant of jdickey/suirdemo#12, adding inline `/* eslint-disable-line */` comments on, e.g., [this line](https://github.com/jdickey/flix/blob/b5e9cec/src/index.js#L3) in `index.js` *does not* prevent ESLint from reporting a (wholly spurious, in this case) `'App' is defined but never used` error. The only way to silence such errors appears to be disabling the relevant rule (here, `no-unused-vars`) *for the entire file.* :nauseated_face:

This issue should remain open until a more granular workaround is implemented and/or whatever is causing ESLint to malfunction (in ESLint proper or as a side effect of `react-scripts`) is repaired.

**Comment by jdickey** [comment]
I think this is still something of a bug in ESLint's parsing, but it turns out that inline comments *do* work if you use them *precisely* [as documented](http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments).

This *will not* work:

```javascript
import App from './App'; /** eslint-disable-line no-unused-vars */
```
But this will:

```javascript
import App from `./App'; // eslint-disable-line no-unused-vars
```
A quibble, you say? I would tend to agree with you; this is as clear a violation of [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle) as I've seen in some time.

**Comment by mitpaladin** [comment]
indeed, that is a fine distinction
